import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import HeaderApp from "@/components/header";
import FooterApp from "@/components/footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"]
})

export const metadata: Metadata = {
  title: "Tìm nhà trọ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" translate="no">
      <body
        className={`${inter.variable}`}
      >
        <HeaderApp />
        {children}
        <FooterApp />
      </body>
    </html>
  );
}
